socket_zmq:
  protocol: tcp #must stay tcp
  ip: 0.0.0.0 #testing purposes
  port: 5555
socket_ssh:
  protocol: tcp #must stay tcp
  ip: 0.0.0.0 #testing purposes
  port: 5555
data_window:
  channels_start: 150
  channels_end: 300
  overlap: 20
  location: "Niscemi"
  leave_file_untouched: False
credentials:
  user: marco
  passwd: marco
data_dir:
  save_path: "data"
  config_dir: "config"
  server_data_dir: "data_dir" #complete_path
  queue_dim: 20
supplement_attribute:
  [
    GaugeLength,
    PulseRateFreq,
    FiberLength,
    SamplingRate,
    AmpliPower,
    DataDomain,
  ]
