socket:
  protocol: tcp #must stay tcp
  ip: 0.0.0.0 #testing purposes
  port: 5555
data_window:
  channels_start: 150
  channels_end: 300
  overlap: 20
  location: "Niscemi"
data_dir:
  save_path: "data"
  queue_dim: 20
