socket:
  protocol: tcp #must stay tcp
  ip: 172.17.69.255 #testing purposes
  port: 22
credentials:
  user: marco
  passwd: marco
paths:
  path_server: /mnt/c/users/marco/Documents/Università/III Anno/Tirocinio/linux_debian/service
  path_local: C:/Users/marco/Documents/Università/III Anno/Tirocinio/prova_copia
  server_save_dir: "prova"
extension: .txt
server_script_name: server_test_ssh.py
